return {
	AutomaticUpdates = false,
	ToggleGUI = true,
	Backrooms = false,
	FastLoad = true,
	KickGui = true,
	Notifications = true,
	DisablePrompts = true,
	AntiAFK = true,
	RejoinOnKick = false,
	ChatFilterLabel = true,
	SecureEnvironment = false,
	DisableConnections = true,
	ExtraGlobals = true,
}
